# Working with lists

In [12]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
type(L[0])

int

In [14]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [15]:
type(L2)[0]

list[0]

In [16]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

As each item in a list can be a different type, each has its own type info. A single-type array is therefore more efficient.

In [17]:
import numpy as np

# Creating arrays from lists

In [18]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [20]:
np.array([1, 2, 3, 4], dtype  = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [21]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# Creating arrays from scratch

In [22]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3, 5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [25]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.random.random((3, 3)) # uniform

array([[0.25069256, 0.28446425, 0.13854595],
       [0.11165965, 0.26221339, 0.32008393],
       [0.14437888, 0.93228697, 0.70259188]])

In [29]:
np.random.normal(0, 1, (3, 3)) # normal/Gaussian

array([[-0.18975858, -0.83276789,  0.25402534],
       [-0.53585421,  1.31456806, -0.80753543],
       [ 0.6989995 ,  0.4871785 ,  1.4425509 ]])

In [30]:
np.random.randint(0, 10, (3, 3)) # equal prob

array([[5, 3, 7],
       [0, 2, 7],
       [5, 3, 8]])

In [31]:
np.eye(3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.empty(3) # uninitalised array, values will be whatever happens to exist at that memory location

array([1., 1., 1.])

# NumPy array attributes

In [36]:
np.random.seed(0)

In [40]:
x1 = np.random.randint(10, size = 6) # 1-dimensional
x2 = np.random.randint(10, size = (3, 4)) # 2-dimensional
x3 = np.random.randint(10, size = (3, 4, 5)) # 3-dimensional
print(x1)
print("")
print(x2)
print("")
print(x3)

[1 1 0 3 8 8]

[[4 4 0 9]
 [3 7 3 2]
 [1 1 2 1]]

[[[4 2 5 5 5]
  [2 5 7 7 6]
  [1 6 7 2 3]
  [1 9 5 9 9]]

 [[2 0 9 1 9]
  [0 6 0 4 8]
  [4 3 3 8 8]
  [7 0 3 8 7]]

 [[7 1 8 4 7]
  [0 4 9 0 6]
  [4 2 4 6 3]
  [3 7 8 5 0]]]
[1 1 0 3 8 8]

[[4 4 0 9]
 [3 7 3 2]
 [1 1 2 1]]

[[[4 2 5 5 5]
  [2 5 7 7 6]
  [1 6 7 2 3]
  [1 9 5 9 9]]

 [[2 0 9 1 9]
  [0 6 0 4 8]
  [4 3 3 8 8]
  [7 0 3 8 7]]

 [[7 1 8 4 7]
  [0 4 9 0 6]
  [4 2 4 6 3]
  [3 7 8 5 0]]]


In [47]:
print('x3 ndim    : ', x3.ndim)  
print('x3 shape   : ', x3.shape) 
print('x3 size    : ', x3.size)
print('x3 dtype   : ', x3.dtype)
print('x3 itemsize: ', x3.itemsize, ' bytes') # size of each element
print('x3 nbytes  : ', x3.nbytes, ' bytes') # total size of the array

x3 ndim    :  3
x3 shape   :  (3, 4, 5)
x3 size    :  60
x3 dtype   :  int64
x3 itemsize:  8  bytes
x3 nbytes  :  480  bytes
x3 ndim    :  3
x3 shape   :  (3, 4, 5)
x3 size    :  60
x3 dtype   :  int64
x3 itemsize:  8  bytes
x3 nbytes  :  480  bytes


# Array indexing

In [48]:
x1

array([1, 1, 0, 3, 8, 8])

In [49]:
x1[0]

1

In [53]:
x1[-2] # from the last element

8

In [54]:
x2

array([[4, 4, 0, 9],
       [3, 7, 3, 2],
       [1, 1, 2, 1]])

In [55]:
x2[0, 0]

4

In [60]:
x2[0, 0] = 12
x2

array([[12,  4,  0,  9],
       [ 3,  7,  3,  2],
       [ 1,  1,  2,  1]])

In [61]:
x1[0] = 3.14 # this will be truncated!

In [66]:
x = np.arange(10)
print(x)
x[:5] # x[start:stop:step]

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4])

In [67]:
x[5:]

array([5, 6, 7, 8, 9])

In [68]:
x[4:7]

array([4, 5, 6])

In [69]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [70]:
x[1::2] # every other element starting at index 1

array([1, 3, 5, 7, 9])

In [71]:
x[::-1] # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [72]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])

In [73]:
x2

array([[12,  4,  0,  9],
       [ 3,  7,  3,  2],
       [ 1,  1,  2,  1]])

In [74]:
x2[:2, :3]

array([[12,  4,  0],
       [ 3,  7,  3]])

In [75]:
x2[:3, ::2] # all rows, every other column

array([[12,  0],
       [ 3,  3],
       [ 1,  2]])

In [80]:
x2[:,0] # get just first column

array([12,  3,  1])

In [83]:
x2[0, ] # get just first row (colon can be omitted)

array([12,  4,  0,  9])

In [84]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  4],
       [ 3,  7]])

In [85]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  4],
       [ 3,  7]])

In [86]:
x2 # notice the original array has changed, i.e. subarrays are *no copy* views

array([[99,  4,  0,  9],
       [ 3,  7,  3,  2],
       [ 1,  1,  2,  1]])

In [87]:
x2_sub_copy = x2[:2, :2].copy() # making a copy leaves the original unchanged
x2_sub_copy[0, 0] = 42
x2

array([[99,  4,  0,  9],
       [ 3,  7,  3,  2],
       [ 1,  1,  2,  1]])

# Reshaping arrays

In [89]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [93]:
x.reshape((1, 3))

array([[1, 2, 3]])

In [94]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [95]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [96]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])